version: "3.9"
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: libraryrms
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: ./apps/api
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/libraryrms?schema=public
    ports:
      - "3000:3000"
    volumes:
      - ./apps/api:/app
      - /app/node_modules

  web:
    build: ./apps/web
    depends_on:
      - api
    ports:
      - "5173:5173"
    volumes:
      - ./apps/web:/app
      - /app/node_modules

volumes:
  postgres_data: