version: "3.9"
services:
  api:
    build: ./apps/api
    container_name: library_api
    ports:
      - "4000:4000"
    env_file:
      - ./.env
    depends_on:
      - db

  web:
    build: ./apps/web
    container_name: library_web
    ports:
      - "3000:80"
    depends_on:
      - api

  db:
    image: postgres:15
    container_name: library_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: jaylorddecano
      POSTGRES_DB: libraryrms
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: